handler: aime
dataset_path: AI-MO/aimo-validation-aime
dataset_split: train
question_key: problem
answer_key: answer
templating_parameters:
  template: "Solve the following math problem efficiently and clearly. Please reason step by step, 
        separate logical reasoning steps with two newline characters (\n\n), and put your final answer within \\boxed{{}}.
        Problem: {prompt} <think>\n"
preprocess_config:
  url: "2024"
