handler: gpqa_diamond
dataset_path: Idavidrein/gpqa
dataset_subset: gpqa_diamond
dataset_split: train
question_key: Question
answer_key: Answer
templating_parameters:
  # For GPQA, we combine the Question key and the multiple choice answers into a single `prompt` entry
  template:  "What is the correct answer to the following problem? Please reason step by step. 
        Separate logical reasoning steps with two newline characters (\n\n).
        Put the final answer **strictly** in the format \\boxed{{X}}, where X is a single letter (A, B, C, or D).

        **Example output:** \\boxed{{A}}

        Problem: {prompt}" 